### PR TITLE
(MCOP-537) - runhosts should not block on a single busy node.

### PR DESCRIPTION
**Pull request by LorcanHamill**
This change addresses both of the problems mentioned in the description of MCOP-537.

This is my first pull request for the MCollective Plugins ; please let me know if there is some other procedure that I need to follow.

Thanks!

### CODE REVIEW

**Comment by LorcanHamill** [comment]
The CI failures seem to be due to a versioning problem.  When I try to install rake locally, I get this:

[lorcan@ffa823c51a5d mcollective-puppet-agent]$ sudo gem install rake -v '11.1.2'
ERROR:  Error installing rake:
        rake requires Ruby version >= 1.9.3.
[lorcan@ffa823c51a5d mcollective-puppet-agent]$

**Comment by MikaelSmith** [comment]
The CI issue has been fixed, mind rebasing to pick it up?

**Comment by LorcanHamill** [comment]
Okay, I'm not sure if I did a rebase or a merge....?     You can tell I'm a github newbie...!

**Comment by MikaelSmith** [comment]
That was definitely a merge. For a rebase you'd do something like
```
git fetch origin # assuming origin is github.com/puppetlabs/mcollective-puppet-agent
git rebase -i origin/master
git push -f <your branch> master
```

One way to clean this up would be to save the SHAs of your changes, do a `git reset --hard origin/master`, then `git cherry-pick <sha>` to bring your changes back in. I would also suggest creating a new branch for your changes. So in total this would look like
```
git checkout -b MCOP-537 origin/master
git reset --hard origin/master
git cherry-pick eb6fb763d105332c7fbba830bd2ddd726735cf02
git push <your branch> MCOP-537
```
and open a new pull request from that branch.

**Comment by LorcanHamill** [comment]
Ok, thanks Mikael.  I'll try to sort that out on Monday - it's Friday evening here.....

**Comment by LorcanHamill** [comment]
@MikaelSmith - sorry, I was away unexpectedly.  Back now to try to sort this out.  As a github newbie I feel that I've got this PR into a mess, so I'm tempted to abandon it and start again.  (The code change is small enough that it's easy to do that - I have a local copy of the code.)  Is there a page somewhere that documents the process your project follows?  Failing that, I'll probably follow the one described here:

[Github Beginner's Guide](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/)

**Comment by MikaelSmith** [comment]
Take a look at https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md for more guidelines. It doesn't really talk through Git commands however, so the Github Beginner's Guide is probably still useful.

**Comment by LorcanHamill** [comment]
Thanks, Mikael, will do.

**Comment by MikaelSmith** [comment]
Closing in favor of https://github.com/puppetlabs/mcollective-puppet-agent/pull/68.

**Pull request closed without merging**
