### PR TITLE
(MCOP-538) Added display of avg values to the puppet summary report

### PR DESCRIPTION
**Pull request by slseed1969**
Relates to issue reported:

https://tickets.puppetlabs.com/browse/MCO-547

### CODE REVIEW

**Comment by ploubser** [comment]
Hi @slseed1969, do you still consider this PR relevant?
If this is still something you would like us to take it, I think signing the CLA will be required, since it technically introduces a new feature. Also, the tests will need to be updated but if necassary we can help with that.

**Comment by slseed1969** [comment]
As it turns out, I just heard from my management and they are reviewing the
agreement to see if I can sign it. Our legal team should be reaching out to
Puppetlabs shortly.

**Comment by MikaelSmith** [comment]
Was this ever resolved?

**Comment by MikaelSmith** [comment]
Closing this given it's been open for a year without activity. If this is still useful, please re-open the PR.

**Comment by slseed1969** [comment]
I signed a CLA on 6/1/15 but nothing was ever updated in this ticket about it. They were supposed to pass it on to engineering. I think this feature is useful and should be implemented.

**Comment by MikaelSmith** [comment]
Ok, that sounds fine. Do you have time to update the failing spec test?

**Comment by slseed1969** [comment]
I'll take a look.

**Comment by slseed1969** [comment]
I added the rspec test fixes. Assuming it fixes the build errors, I think it should be ready to merge.

**Pull request merged**
