### PR TITLE
Mergeup for 1.11.1 release

### PR DESCRIPTION
**Pull request by underscorgan**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Want to rebase on the CI fix?

**Comment by underscorgan** [comment]
done!

**Comment by ripienaar** [comment]
this ticket is private so cant comment there - but are you tagging a new release of this?

**Comment by MikaelSmith** [comment]
The tag was merged, I should be able to make MCOP-557 and 559 public though.

**Comment by ripienaar** [comment]
right, guess I was blind and didn't see it :) thanks

**Pull request merged**
